const mysql = require('mysql');
const express = require('express');
const router = express.Router();
const multer = require('multer');
const path = require('path');

// Middleware to parse JSON and URL-encoded bodies from Postman
router.use(express.json());
router.use(express.urlencoded({ extended: true }));

// Connect to Database
const con = require('../../config/db');

// ✅ MULTER CONFIG FOR SCHOOL IMAGES
const imageStorage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, 'images/');
  },
  filename: (req, file, cb) => {
    // Save with timestamp and original extension
    const ext = path.extname(file.originalname);
    cb(null, 'school_' + Date.now() + ext);
  }
});

const imageUpload = multer({ 
  storage: imageStorage,
  fileFilter: (req, file, cb) => {
    // Only allow image files
    const allowedTypes = /jpeg|jpg|png|gif|webp/;
    const extname = allowedTypes.test(path.extname(file.originalname).toLowerCase());
    const mimetype = allowedTypes.test(file.mimetype);
    
    if (mimetype && extname) {
      return cb(null, true);
    } else {
      cb(new Error('Only image files are allowed'));
    }
  }
});
router.get('/', (req, res) => {
  res.status(200).send("<H1>Welcome TO school.service.js Server</H1>");
});

// GET /school      -> all school
router.get('/school', (req, res) => {
    const School_ID = req.query.id;
  
    let sql = 'SELECT * FROM school';
    let params = [];
  
    if (School_ID && School_ID !== '%') {
      const idNum = Number(School_ID);
      if (!Number.isInteger(idNum)) {
        return res.status(400).json({ error: "Query param 'id' must be an integer or '%'." });
      }
  
      sql += ' WHERE School_ID = ?';
      params = [idNum];
    }
  
    con.query(sql, params, function (err, result, fields) {
      if (err) {
        console.error('DB query failed:', err.message);
        return res.status(500).json({ error: err.message });
      }
      res.json(result);
      console.log(result);
    });
  });
   // POST /school to create a new record with image upload
   router.post('/school', imageUpload.single('image'), (req, res) => {
    console.log("POST /school - Request Received", req.body);
    console.log("File:", req.file);
  
    const { Name, Address, Rating, Special_Need_Prog, Website_Link, P_ID } = req.body || {};
    const imageFilename = req.file ? req.file.filename : null;
  
    // Validation
    if (!Name || !Address || !Rating || !Special_Need_Prog || !Website_Link || !P_ID) {
      return res.status(400).json({ 
        Status: "Error", 
        Message: "Name, Address, Rating, Special_Need_Prog, Website_Link, and P_ID are required" 
      });
    }

    if (!imageFilename) {
      return res.status(400).json({ 
        Status: "Error", 
        Message: "School image is required" 
      });
    }
  
    // Insert school without School_ID (auto-generated by DB)
    const sql = "INSERT INTO school (`Name`, `Address`, `Rating`, `Special_Need_Prog`, `Website_Link`, `Image`, `P_ID`) VALUES (?, ?, ?, ?, ?, ?, ?)";
  
    con.query(sql, [Name, Address, Rating, Special_Need_Prog, Website_Link, imageFilename, P_ID], function (err, result, fields) {
      if (err) {
        console.error("❌ Insert failed:", err.message);
        return res.status(500).json({ Status: "Error", Message: err.message });
      }
      console.log("✅ School Added with ID:", result.insertId);
      res.status(201).json({ 
        Status: "OK", 
        Message: "School added successfully", 
        School_ID: result.insertId,
        Image: imageFilename
      });
    });
  });
  //del
  router.delete('/school',(req,res)=>{
    var School_ID= req.query.id;
    con.query("DELETE FROM school where School_ID = ?", [School_ID], function (err, result, fields) {
      if (err) throw err;
      if (result.affectedRows === 0) {
        return res.status(404).json({
          Status: "Not Found",
          Message: "Record Id [" + School_ID + "] does not exist"
        });
      }
      res.json({"Status":"OK", "Message" : "Record Id ["+req.query.id+"] deleted Successfully"});
      console.log("Delete Request Received for record ["+req.query.id+"] received");
    });
  });
  //put - Update school with optional image
  router.put('/school', imageUpload.single('image'), (req, res) => {
    console.log("PUT /school - Update Request Received");
    var School_ID = req.query.id;

    if (!School_ID) {
      return res.status(400).json({
        Status: "Error",
        Message: "School_ID is required"
      });
    }

    // Get existing school to check if image is being updated
    con.query("SELECT Image FROM school WHERE School_ID = ?", [School_ID], (selectErr, selectResult) => {
      if (selectErr) {
        return res.status(500).json({ Status: "Error", Message: selectErr.message });
      }

      if (!selectResult || selectResult.length === 0) {
        return res.status(404).json({ Status: "Error", Message: "School not found" });
      }

      // Use new image if provided, otherwise keep existing
      const imageFilename = req.file ? req.file.filename : selectResult[0].Image;

      con.query(
        "UPDATE school SET `Name` = ?, `Address` = ?, `Rating` = ?, `Special_Need_Prog` = ?, `Website_Link` = ?, `Image` = ?, `P_ID` = ? WHERE School_ID = ?",
        [
          req.body.Name,
          req.body.Address,
          req.body.Rating,
          req.body.Special_Need_Prog,
          req.body.Website_Link,
          imageFilename,
          req.body.P_ID,
          School_ID
        ],
        function (err, result, fields) {
          if (err) {
            console.error("❌ Update failed:", err.message);
            return res.status(500).json({ "Status": "Error", "Message": err.message });
          }
           if (result.affectedRows === 0) {
          return res.status(404).json({
            "Status": "Error",
            "Message": "Record not found"
          });
        }

        if (result.changedRows === 0) {
          return res.json({
            "Status": "OK",
            "Message": "No changes made (same data sent)"
          });
        }
         console.log("✅ School ID [" + School_ID + "] is Updated Successfully");
         return res.json({ 
          "Status": "OK", 
          "Message": "School ID [" + School_ID + "] is Updated Successfully",
          "Image": imageFilename
        });
        }
      );
    });
  });
  //SEARCH
router.get('/search', (req, res) => {
  keyword = req.query.keyword;
  keyvalue = req.query.keyvalue;
  sort = req.query.sort;

  con.query(
      "SELECT * FROM school where " + keyword + " = ? order by School_ID  " + sort,
      [keyvalue],
      function (err, result, fields) {
          if (err) {
              res.json({ "Status": "Error", "Message": err });
          } else {
              res.json(result);
              console.log(result);
          }
      }
  );

  console.log('Incoming SEARCH Request');
});

module.exports = router;